# Generated by Django 3.1.4 on 2021-01-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210103_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='quantity_available',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
