# Generated by Django 3.1.4 on 2021-01-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_products_quantity_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
