# Generated by Django 3.1.4 on 2021-01-05 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210105_1651'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderProducts',
            new_name='OrderProduct',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
