# Generated by Django 3.1.4 on 2021-01-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_order_placed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='placed_on',
            field=models.DateTimeField(null=True),
        ),
    ]
