# Generated by Django 3.1.4 on 2021-01-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210114_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, unique=True)),
                ('amount', models.FloatField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField()),
                ('discount_percentage', models.PositiveIntegerField()),
            ],
        ),
    ]
