# Generated by Django 3.1.4 on 2021-01-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_percentage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
