# Generated by Django 3.1.4 on 2021-01-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.FloatField(default=None, null=True),
        ),
    ]
