# Generated by Django 3.1.4 on 2021-01-18 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
    ]
